package com.school.domain.entity;
// Generated Jul 12, 2018 5:22:44 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * AttendanceReportType generated by hbm2java
 */
@Entity
@Table(name="attendance_report_type"
    ,catalog="db_school"
)
public class AttendanceReportType  implements java.io.Serializable {


     private Integer reportTypeId;
     private String typeName;

    public AttendanceReportType() {
    }

    public AttendanceReportType(String typeName) {
       this.typeName = typeName;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="report_type_id", unique=true, nullable=false)
    public Integer getReportTypeId() {
        return this.reportTypeId;
    }
    
    public void setReportTypeId(Integer reportTypeId) {
        this.reportTypeId = reportTypeId;
    }

    
    @Column(name="type_name", nullable=false, length=45)
    public String getTypeName() {
        return this.typeName;
    }
    
    public void setTypeName(String typeName) {
        this.typeName = typeName;
    }




}


