package com.school.domain.entity;
// Generated Jul 9, 2018 4:05:01 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * AttendanceReport generated by hbm2java
 */
@Entity
@Table(name="attendance_report"
    ,catalog="db_school"
)
public class AttendanceReport  implements java.io.Serializable {


     private Integer attendanceReportId;
     private StudentRecordBs studentRecordBs;
     private int totalPresents;
     private int totalAbsents;
     private int monthId;

    public AttendanceReport() {
    }

    public AttendanceReport(StudentRecordBs studentRecordBs, int totalPresents, int totalAbsents, int monthId) {
       this.studentRecordBs = studentRecordBs;
       this.totalPresents = totalPresents;
       this.totalAbsents = totalAbsents;
       this.monthId = monthId;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="attendance_report_id", unique=true, nullable=false)
    public Integer getAttendanceReportId() {
        return this.attendanceReportId;
    }
    
    public void setAttendanceReportId(Integer attendanceReportId) {
        this.attendanceReportId = attendanceReportId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="record_bs_id", nullable=false)
    public StudentRecordBs getStudentRecordBs() {
        return this.studentRecordBs;
    }
    
    public void setStudentRecordBs(StudentRecordBs studentRecordBs) {
        this.studentRecordBs = studentRecordBs;
    }

    
    @Column(name="total_presents", nullable=false)
    public int getTotalPresents() {
        return this.totalPresents;
    }
    
    public void setTotalPresents(int totalPresents) {
        this.totalPresents = totalPresents;
    }

    
    @Column(name="total_absents", nullable=false)
    public int getTotalAbsents() {
        return this.totalAbsents;
    }
    
    public void setTotalAbsents(int totalAbsents) {
        this.totalAbsents = totalAbsents;
    }

    
    @Column(name="month_id", nullable=false)
    public int getMonthId() {
        return this.monthId;
    }
    
    public void setMonthId(int monthId) {
        this.monthId = monthId;
    }




}


