package com.school.domain.entity;
// Generated Jul 9, 2018 4:05:01 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Attendance generated by hbm2java
 */
@Entity
@Table(name="attendance"
    ,catalog="db_school"
)
public class Attendance  implements java.io.Serializable {


     private Integer attendanceId;
     private Groups groups;
     private StudentRecordBs studentRecordBs;
     private Users users;
     private boolean attendanceStatus;
     private Date attendanceDate;

    public Attendance() {
    }

    public Attendance(Groups groups, StudentRecordBs studentRecordBs, Users users, boolean attendanceStatus, Date attendanceDate) {
       this.groups = groups;
       this.studentRecordBs = studentRecordBs;
       this.users = users;
       this.attendanceStatus = attendanceStatus;
       this.attendanceDate = attendanceDate;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="attendance_id", unique=true, nullable=false)
    public Integer getAttendanceId() {
        return this.attendanceId;
    }
    
    public void setAttendanceId(Integer attendanceId) {
        this.attendanceId = attendanceId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="group_id", nullable=false)
    public Groups getGroups() {
        return this.groups;
    }
    
    public void setGroups(Groups groups) {
        this.groups = groups;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="record_bs_id", nullable=false)
    public StudentRecordBs getStudentRecordBs() {
        return this.studentRecordBs;
    }
    
    public void setStudentRecordBs(StudentRecordBs studentRecordBs) {
        this.studentRecordBs = studentRecordBs;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_id", nullable=false)
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }

    
    @Column(name="attendance_status", nullable=false)
    public boolean isAttendanceStatus() {
        return this.attendanceStatus;
    }
    
    public void setAttendanceStatus(boolean attendanceStatus) {
        this.attendanceStatus = attendanceStatus;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="attendance_date", nullable=false, length=0)
    public Date getAttendanceDate() {
        return this.attendanceDate;
    }
    
    public void setAttendanceDate(Date attendanceDate) {
        this.attendanceDate = attendanceDate;
    }




}


