package com.school.domain.entity;
// Generated Jul 9, 2018 4:05:01 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Classes generated by hbm2java
 */
@Entity
@Table(name="classes"
    ,catalog="db_school"
)
public class Classes  implements java.io.Serializable {


     private Integer classId;
     private String className;
     private Set<TeacherClasses> teacherClasseses = new HashSet<TeacherClasses>(0);
     private Set<StPaymentByClass> stPaymentByClasses = new HashSet<StPaymentByClass>(0);
     private Set<StudentRecordBs> studentRecordBses = new HashSet<StudentRecordBs>(0);

    public Classes() {
    }

	
    public Classes(String className) {
        this.className = className;
    }
    public Classes(String className, Set<TeacherClasses> teacherClasseses, Set<StPaymentByClass> stPaymentByClasses, Set<StudentRecordBs> studentRecordBses) {
       this.className = className;
       this.teacherClasseses = teacherClasseses;
       this.stPaymentByClasses = stPaymentByClasses;
       this.studentRecordBses = studentRecordBses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="class_id", unique=true, nullable=false)
    public Integer getClassId() {
        return this.classId;
    }
    
    public void setClassId(Integer classId) {
        this.classId = classId;
    }

    
    @Column(name="class_name", nullable=false, length=45)
    public String getClassName() {
        return this.className;
    }
    
    public void setClassName(String className) {
        this.className = className;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="classes")
    public Set<TeacherClasses> getTeacherClasseses() {
        return this.teacherClasseses;
    }
    
    public void setTeacherClasseses(Set<TeacherClasses> teacherClasseses) {
        this.teacherClasseses = teacherClasseses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="classes")
    public Set<StPaymentByClass> getStPaymentByClasses() {
        return this.stPaymentByClasses;
    }
    
    public void setStPaymentByClasses(Set<StPaymentByClass> stPaymentByClasses) {
        this.stPaymentByClasses = stPaymentByClasses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="classes")
    public Set<StudentRecordBs> getStudentRecordBses() {
        return this.studentRecordBses;
    }
    
    public void setStudentRecordBses(Set<StudentRecordBs> studentRecordBses) {
        this.studentRecordBses = studentRecordBses;
    }




}


