package com.school.domain.entity;
// Generated Jul 9, 2018 4:05:01 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Grade generated by hbm2java
 */
@Entity
@Table(name="grade"
    ,catalog="db_school"
)
public class Grade  implements java.io.Serializable {


     private Integer gradeId;
     private String gradeName;
     private double gradePoint;
     private double parcentage;
     private Set<Marks> markses = new HashSet<Marks>(0);

    public Grade() {
    }

	
    public Grade(String gradeName, double gradePoint, double parcentage) {
        this.gradeName = gradeName;
        this.gradePoint = gradePoint;
        this.parcentage = parcentage;
    }
    public Grade(String gradeName, double gradePoint, double parcentage, Set<Marks> markses) {
       this.gradeName = gradeName;
       this.gradePoint = gradePoint;
       this.parcentage = parcentage;
       this.markses = markses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="grade_id", unique=true, nullable=false)
    public Integer getGradeId() {
        return this.gradeId;
    }
    
    public void setGradeId(Integer gradeId) {
        this.gradeId = gradeId;
    }

    
    @Column(name="grade_name", nullable=false, length=45)
    public String getGradeName() {
        return this.gradeName;
    }
    
    public void setGradeName(String gradeName) {
        this.gradeName = gradeName;
    }

    
    @Column(name="grade_point", nullable=false, precision=22, scale=0)
    public double getGradePoint() {
        return this.gradePoint;
    }
    
    public void setGradePoint(double gradePoint) {
        this.gradePoint = gradePoint;
    }

    
    @Column(name="parcentage", nullable=false, precision=22, scale=0)
    public double getParcentage() {
        return this.parcentage;
    }
    
    public void setParcentage(double parcentage) {
        this.parcentage = parcentage;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="grade")
    public Set<Marks> getMarkses() {
        return this.markses;
    }
    
    public void setMarkses(Set<Marks> markses) {
        this.markses = markses;
    }




}


