package com.school.domain.entity;
// Generated Aug 3, 2018 10:07:42 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Marks generated by hbm2java
 */
@Entity
@Table(name="marks"
    ,catalog="db_school"
)
public class Marks  implements java.io.Serializable {


     private Integer marksId;
     private Exams exams;
     private Grade grade;
     private StudentRecordBs studentRecordBs;
     private Subjects subjects;
     private int writtenMarks;
     private int mcqMarks;
     private int practicalMarks;

    public Marks() {
    }

    public Marks(Exams exams, Grade grade, StudentRecordBs studentRecordBs, Subjects subjects, int writtenMarks, int mcqMarks, int practicalMarks) {
       this.exams = exams;
       this.grade = grade;
       this.studentRecordBs = studentRecordBs;
       this.subjects = subjects;
       this.writtenMarks = writtenMarks;
       this.mcqMarks = mcqMarks;
       this.practicalMarks = practicalMarks;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="marks_id", unique=true, nullable=false)
    public Integer getMarksId() {
        return this.marksId;
    }
    
    public void setMarksId(Integer marksId) {
        this.marksId = marksId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="exam_id", nullable=false)
    public Exams getExams() {
        return this.exams;
    }
    
    public void setExams(Exams exams) {
        this.exams = exams;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="grade_id", nullable=false)
    public Grade getGrade() {
        return this.grade;
    }
    
    public void setGrade(Grade grade) {
        this.grade = grade;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="record_bs_id", nullable=false)
    public StudentRecordBs getStudentRecordBs() {
        return this.studentRecordBs;
    }
    
    public void setStudentRecordBs(StudentRecordBs studentRecordBs) {
        this.studentRecordBs = studentRecordBs;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="subject_id", nullable=false)
    public Subjects getSubjects() {
        return this.subjects;
    }
    
    public void setSubjects(Subjects subjects) {
        this.subjects = subjects;
    }

    
    @Column(name="written_marks", nullable=false)
    public int getWrittenMarks() {
        return this.writtenMarks;
    }
    
    public void setWrittenMarks(int writtenMarks) {
        this.writtenMarks = writtenMarks;
    }

    
    @Column(name="mcq_marks", nullable=false)
    public int getMcqMarks() {
        return this.mcqMarks;
    }
    
    public void setMcqMarks(int mcqMarks) {
        this.mcqMarks = mcqMarks;
    }

    
    @Column(name="practical_marks", nullable=false)
    public int getPracticalMarks() {
        return this.practicalMarks;
    }
    
    public void setPracticalMarks(int practicalMarks) {
        this.practicalMarks = practicalMarks;
    }




}


