package com.school.domain.entity;
// Generated Jul 12, 2018 5:22:44 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Months generated by hbm2java
 */
@Entity
@Table(name="months"
    ,catalog="db_school"
)
public class Months  implements java.io.Serializable {


     private Integer monthId;
     private String monthName;
     private Set<AttendanceReport> attendanceReports = new HashSet<AttendanceReport>(0);

    public Months() {
    }

	
    public Months(String monthName) {
        this.monthName = monthName;
    }
    public Months(String monthName, Set<AttendanceReport> attendanceReports) {
       this.monthName = monthName;
       this.attendanceReports = attendanceReports;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="month_id", unique=true, nullable=false)
    public Integer getMonthId() {
        return this.monthId;
    }
    
    public void setMonthId(Integer monthId) {
        this.monthId = monthId;
    }

    
    @Column(name="month_name", nullable=false, length=45)
    public String getMonthName() {
        return this.monthName;
    }
    
    public void setMonthName(String monthName) {
        this.monthName = monthName;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="months")
    public Set<AttendanceReport> getAttendanceReports() {
        return this.attendanceReports;
    }
    
    public void setAttendanceReports(Set<AttendanceReport> attendanceReports) {
        this.attendanceReports = attendanceReports;
    }




}


