package com.school.domain.entity;
// Generated Jul 9, 2018 4:05:01 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Notice generated by hbm2java
 */
@Entity
@Table(name="notice"
    ,catalog="db_school"
)
public class Notice  implements java.io.Serializable {


     private Integer noticeId;
     private String fileLocation;
     private Date noticeDate;
     private boolean noticeStatus;

    public Notice() {
    }

    public Notice(String fileLocation, Date noticeDate, boolean noticeStatus) {
       this.fileLocation = fileLocation;
       this.noticeDate = noticeDate;
       this.noticeStatus = noticeStatus;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="notice_id", unique=true, nullable=false)
    public Integer getNoticeId() {
        return this.noticeId;
    }
    
    public void setNoticeId(Integer noticeId) {
        this.noticeId = noticeId;
    }

    
    @Column(name="file_location", nullable=false, length=45)
    public String getFileLocation() {
        return this.fileLocation;
    }
    
    public void setFileLocation(String fileLocation) {
        this.fileLocation = fileLocation;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="notice_date", nullable=false, length=0)
    public Date getNoticeDate() {
        return this.noticeDate;
    }
    
    public void setNoticeDate(Date noticeDate) {
        this.noticeDate = noticeDate;
    }

    
    @Column(name="notice_status", nullable=false)
    public boolean isNoticeStatus() {
        return this.noticeStatus;
    }
    
    public void setNoticeStatus(boolean noticeStatus) {
        this.noticeStatus = noticeStatus;
    }




}


