package com.school.domain.entity;
// Generated Jul 9, 2018 4:05:01 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ProgressReport generated by hbm2java
 */
@Entity
@Table(name="progress_report"
    ,catalog="db_school"
)
public class ProgressReport  implements java.io.Serializable {


     private Integer progressReportId;
     private StudentRecordBs studentRecordBs;
     private int firstTermMarks;
     private int secondTermMarks;
     private int finalMarks;
     private double avgMarks;
     private double persentageMarks;

    public ProgressReport() {
    }

    public ProgressReport(StudentRecordBs studentRecordBs, int firstTermMarks, int secondTermMarks, int finalMarks, double avgMarks, double persentageMarks) {
       this.studentRecordBs = studentRecordBs;
       this.firstTermMarks = firstTermMarks;
       this.secondTermMarks = secondTermMarks;
       this.finalMarks = finalMarks;
       this.avgMarks = avgMarks;
       this.persentageMarks = persentageMarks;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="progress_report_id", unique=true, nullable=false)
    public Integer getProgressReportId() {
        return this.progressReportId;
    }
    
    public void setProgressReportId(Integer progressReportId) {
        this.progressReportId = progressReportId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="record_bs_id", nullable=false)
    public StudentRecordBs getStudentRecordBs() {
        return this.studentRecordBs;
    }
    
    public void setStudentRecordBs(StudentRecordBs studentRecordBs) {
        this.studentRecordBs = studentRecordBs;
    }

    
    @Column(name="first_term_marks", nullable=false)
    public int getFirstTermMarks() {
        return this.firstTermMarks;
    }
    
    public void setFirstTermMarks(int firstTermMarks) {
        this.firstTermMarks = firstTermMarks;
    }

    
    @Column(name="second_term_marks", nullable=false)
    public int getSecondTermMarks() {
        return this.secondTermMarks;
    }
    
    public void setSecondTermMarks(int secondTermMarks) {
        this.secondTermMarks = secondTermMarks;
    }

    
    @Column(name="final_marks", nullable=false)
    public int getFinalMarks() {
        return this.finalMarks;
    }
    
    public void setFinalMarks(int finalMarks) {
        this.finalMarks = finalMarks;
    }

    
    @Column(name="avg_marks", nullable=false, precision=22, scale=0)
    public double getAvgMarks() {
        return this.avgMarks;
    }
    
    public void setAvgMarks(double avgMarks) {
        this.avgMarks = avgMarks;
    }

    
    @Column(name="persentage_marks", nullable=false, precision=22, scale=0)
    public double getPersentageMarks() {
        return this.persentageMarks;
    }
    
    public void setPersentageMarks(double persentageMarks) {
        this.persentageMarks = persentageMarks;
    }




}


