package com.school.domain.entity;
// Generated Jul 9, 2018 4:05:01 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * RoutineSedule generated by hbm2java
 */
@Entity
@Table(name="routine_sedule"
    ,catalog="db_school"
)
public class RoutineSedule  implements java.io.Serializable {


     private Integer seduleId;
     private Date classStartTime;
     private Date classEndTime;
     private String seduleName;
     private Set<RoutineMaintainer> routineMaintainers = new HashSet<RoutineMaintainer>(0);

    public RoutineSedule() {
    }

	
    public RoutineSedule(Date classStartTime, Date classEndTime, String seduleName) {
        this.classStartTime = classStartTime;
        this.classEndTime = classEndTime;
        this.seduleName = seduleName;
    }
    public RoutineSedule(Date classStartTime, Date classEndTime, String seduleName, Set<RoutineMaintainer> routineMaintainers) {
       this.classStartTime = classStartTime;
       this.classEndTime = classEndTime;
       this.seduleName = seduleName;
       this.routineMaintainers = routineMaintainers;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="sedule_id", unique=true, nullable=false)
    public Integer getSeduleId() {
        return this.seduleId;
    }
    
    public void setSeduleId(Integer seduleId) {
        this.seduleId = seduleId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="class_start_time", nullable=false, length=0)
    public Date getClassStartTime() {
        return this.classStartTime;
    }
    
    public void setClassStartTime(Date classStartTime) {
        this.classStartTime = classStartTime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="class_end_time", nullable=false, length=0)
    public Date getClassEndTime() {
        return this.classEndTime;
    }
    
    public void setClassEndTime(Date classEndTime) {
        this.classEndTime = classEndTime;
    }

    
    @Column(name="sedule_name", nullable=false, length=45)
    public String getSeduleName() {
        return this.seduleName;
    }
    
    public void setSeduleName(String seduleName) {
        this.seduleName = seduleName;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="routineSedule")
    public Set<RoutineMaintainer> getRoutineMaintainers() {
        return this.routineMaintainers;
    }
    
    public void setRoutineMaintainers(Set<RoutineMaintainer> routineMaintainers) {
        this.routineMaintainers = routineMaintainers;
    }




}


