package com.school.domain.entity;
// Generated Jul 9, 2018 4:05:01 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * RoutineMaintainer generated by hbm2java
 */
@Entity
@Table(name="routine_maintainer"
    ,catalog="db_school"
)
public class RoutineMaintainer  implements java.io.Serializable {


     private Integer routineMaintainId;
     private RoutineSedule routineSedule;
     private StudentRecordBs studentRecordBs;
     private Users users;

    public RoutineMaintainer() {
    }

    public RoutineMaintainer(RoutineSedule routineSedule, StudentRecordBs studentRecordBs, Users users) {
       this.routineSedule = routineSedule;
       this.studentRecordBs = studentRecordBs;
       this.users = users;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="routine_maintain_id", unique=true, nullable=false)
    public Integer getRoutineMaintainId() {
        return this.routineMaintainId;
    }
    
    public void setRoutineMaintainId(Integer routineMaintainId) {
        this.routineMaintainId = routineMaintainId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="sedule_id", nullable=false)
    public RoutineSedule getRoutineSedule() {
        return this.routineSedule;
    }
    
    public void setRoutineSedule(RoutineSedule routineSedule) {
        this.routineSedule = routineSedule;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="record_bs_id", nullable=false)
    public StudentRecordBs getStudentRecordBs() {
        return this.studentRecordBs;
    }
    
    public void setStudentRecordBs(StudentRecordBs studentRecordBs) {
        this.studentRecordBs = studentRecordBs;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_id", nullable=false)
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }




}


