package com.school.domain.entity;
// Generated Jul 9, 2018 4:05:01 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Section generated by hbm2java
 */
@Entity
@Table(name="section"
    ,catalog="db_school"
)
public class Section  implements java.io.Serializable {


     private Integer sectionId;
     private String sectionName;
     private Set<StudentRecordBs> studentRecordBses = new HashSet<StudentRecordBs>(0);

    public Section() {
    }

	
    public Section(String sectionName) {
        this.sectionName = sectionName;
    }
    public Section(String sectionName, Set<StudentRecordBs> studentRecordBses) {
       this.sectionName = sectionName;
       this.studentRecordBses = studentRecordBses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="section_id", unique=true, nullable=false)
    public Integer getSectionId() {
        return this.sectionId;
    }
    
    public void setSectionId(Integer sectionId) {
        this.sectionId = sectionId;
    }

    
    @Column(name="section_name", nullable=false, length=45)
    public String getSectionName() {
        return this.sectionName;
    }
    
    public void setSectionName(String sectionName) {
        this.sectionName = sectionName;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="section")
    public Set<StudentRecordBs> getStudentRecordBses() {
        return this.studentRecordBses;
    }
    
    public void setStudentRecordBses(Set<StudentRecordBs> studentRecordBses) {
        this.studentRecordBses = studentRecordBses;
    }




}


