package com.school.domain.entity;
// Generated Jul 9, 2018 4:05:01 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * StPaymentByClass generated by hbm2java
 */
@Entity
@Table(name="st_payment_by_class"
    ,catalog="db_school"
)
public class StPaymentByClass  implements java.io.Serializable {


     private Integer paymentByClsId;
     private Classes classes;
     private StudentPaymentType studentPaymentType;
     private int paymentAmount;
     private Set<StudentPayment> studentPayments = new HashSet<StudentPayment>(0);

    public StPaymentByClass() {
    }

	
    public StPaymentByClass(Classes classes, StudentPaymentType studentPaymentType, int paymentAmount) {
        this.classes = classes;
        this.studentPaymentType = studentPaymentType;
        this.paymentAmount = paymentAmount;
    }
    public StPaymentByClass(Classes classes, StudentPaymentType studentPaymentType, int paymentAmount, Set<StudentPayment> studentPayments) {
       this.classes = classes;
       this.studentPaymentType = studentPaymentType;
       this.paymentAmount = paymentAmount;
       this.studentPayments = studentPayments;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="payment_by_cls_id", unique=true, nullable=false)
    public Integer getPaymentByClsId() {
        return this.paymentByClsId;
    }
    
    public void setPaymentByClsId(Integer paymentByClsId) {
        this.paymentByClsId = paymentByClsId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="class_id", nullable=false)
    public Classes getClasses() {
        return this.classes;
    }
    
    public void setClasses(Classes classes) {
        this.classes = classes;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="st_payment_tp_id", nullable=false)
    public StudentPaymentType getStudentPaymentType() {
        return this.studentPaymentType;
    }
    
    public void setStudentPaymentType(StudentPaymentType studentPaymentType) {
        this.studentPaymentType = studentPaymentType;
    }

    
    @Column(name="payment_amount", nullable=false)
    public int getPaymentAmount() {
        return this.paymentAmount;
    }
    
    public void setPaymentAmount(int paymentAmount) {
        this.paymentAmount = paymentAmount;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="stPaymentByClass")
    public Set<StudentPayment> getStudentPayments() {
        return this.studentPayments;
    }
    
    public void setStudentPayments(Set<StudentPayment> studentPayments) {
        this.studentPayments = studentPayments;
    }




}


