package com.school.domain.entity;
// Generated Jul 9, 2018 4:05:01 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * StudentRecordDt generated by hbm2java
 */
@Entity
@Table(name="student_record_dt"
    ,catalog="db_school"
)
public class StudentRecordDt  implements java.io.Serializable {


     private Integer recordDtId;
     private int rollNumber;
     private int userId;
     private Set<Marks> markses = new HashSet<Marks>(0);

    public StudentRecordDt() {
    }

	
    public StudentRecordDt(int rollNumber, int userId) {
        this.rollNumber = rollNumber;
        this.userId = userId;
    }
    public StudentRecordDt(int rollNumber, int userId, Set<Marks> markses) {
       this.rollNumber = rollNumber;
       this.userId = userId;
       this.markses = markses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="record_dt_id", unique=true, nullable=false)
    public Integer getRecordDtId() {
        return this.recordDtId;
    }
    
    public void setRecordDtId(Integer recordDtId) {
        this.recordDtId = recordDtId;
    }

    
    @Column(name="roll_number", nullable=false)
    public int getRollNumber() {
        return this.rollNumber;
    }
    
    public void setRollNumber(int rollNumber) {
        this.rollNumber = rollNumber;
    }

    
    @Column(name="user_id", nullable=false)
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="studentRecordDt")
    public Set<Marks> getMarkses() {
        return this.markses;
    }
    
    public void setMarkses(Set<Marks> markses) {
        this.markses = markses;
    }




}


