package com.school.domain.entity;
// Generated Jul 9, 2018 4:05:01 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * StudentPayment generated by hbm2java
 */
@Entity
@Table(name="student_payment"
    ,catalog="db_school"
)
public class StudentPayment  implements java.io.Serializable {


     private Integer studentPaymentId;
     private StPaymentByClass stPaymentByClass;
     private StudentRecordBs studentRecordBs;
     private int paymentId;

    public StudentPayment() {
    }

    public StudentPayment(StPaymentByClass stPaymentByClass, StudentRecordBs studentRecordBs, int paymentId) {
       this.stPaymentByClass = stPaymentByClass;
       this.studentRecordBs = studentRecordBs;
       this.paymentId = paymentId;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="student_payment_id", unique=true, nullable=false)
    public Integer getStudentPaymentId() {
        return this.studentPaymentId;
    }
    
    public void setStudentPaymentId(Integer studentPaymentId) {
        this.studentPaymentId = studentPaymentId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="payment_by_cls_id", nullable=false)
    public StPaymentByClass getStPaymentByClass() {
        return this.stPaymentByClass;
    }
    
    public void setStPaymentByClass(StPaymentByClass stPaymentByClass) {
        this.stPaymentByClass = stPaymentByClass;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="record_bs_id", nullable=false)
    public StudentRecordBs getStudentRecordBs() {
        return this.studentRecordBs;
    }
    
    public void setStudentRecordBs(StudentRecordBs studentRecordBs) {
        this.studentRecordBs = studentRecordBs;
    }

    
    @Column(name="payment_id", nullable=false)
    public int getPaymentId() {
        return this.paymentId;
    }
    
    public void setPaymentId(int paymentId) {
        this.paymentId = paymentId;
    }




}


