package com.school.domain.entity;
// Generated Jul 9, 2018 4:05:01 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * StudentSession generated by hbm2java
 */
@Entity
@Table(name="student_session"
    ,catalog="db_school"
)
public class StudentSession  implements java.io.Serializable {


     private Integer sessionId;
     private String sessionName;
     private Set<StudentRecordBs> studentRecordBses = new HashSet<StudentRecordBs>(0);

    public StudentSession() {
    }

	
    public StudentSession(String sessionName) {
        this.sessionName = sessionName;
    }
    public StudentSession(String sessionName, Set<StudentRecordBs> studentRecordBses) {
       this.sessionName = sessionName;
       this.studentRecordBses = studentRecordBses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="session_id", unique=true, nullable=false)
    public Integer getSessionId() {
        return this.sessionId;
    }
    
    public void setSessionId(Integer sessionId) {
        this.sessionId = sessionId;
    }

    
    @Column(name="session_name", nullable=false, length=45)
    public String getSessionName() {
        return this.sessionName;
    }
    
    public void setSessionName(String sessionName) {
        this.sessionName = sessionName;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="studentSession")
    public Set<StudentRecordBs> getStudentRecordBses() {
        return this.studentRecordBses;
    }
    
    public void setStudentRecordBses(Set<StudentRecordBs> studentRecordBses) {
        this.studentRecordBses = studentRecordBses;
    }




}


