package com.school.domain.entity;
// Generated Jul 9, 2018 4:05:01 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * StudentPaymentType generated by hbm2java
 */
@Entity
@Table(name="student_payment_type"
    ,catalog="db_school"
)
public class StudentPaymentType  implements java.io.Serializable {


     private Integer stPaymentTpId;
     private String typeName;
     private Set<StPaymentByClass> stPaymentByClasses = new HashSet<StPaymentByClass>(0);

    public StudentPaymentType() {
    }

	
    public StudentPaymentType(String typeName) {
        this.typeName = typeName;
    }
    public StudentPaymentType(String typeName, Set<StPaymentByClass> stPaymentByClasses) {
       this.typeName = typeName;
       this.stPaymentByClasses = stPaymentByClasses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="st_payment_tp_id", unique=true, nullable=false)
    public Integer getStPaymentTpId() {
        return this.stPaymentTpId;
    }
    
    public void setStPaymentTpId(Integer stPaymentTpId) {
        this.stPaymentTpId = stPaymentTpId;
    }

    
    @Column(name="type_name", nullable=false, length=45)
    public String getTypeName() {
        return this.typeName;
    }
    
    public void setTypeName(String typeName) {
        this.typeName = typeName;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="studentPaymentType")
    public Set<StPaymentByClass> getStPaymentByClasses() {
        return this.stPaymentByClasses;
    }
    
    public void setStPaymentByClasses(Set<StPaymentByClass> stPaymentByClasses) {
        this.stPaymentByClasses = stPaymentByClasses;
    }




}


