package com.school.domain;
// Generated Jul 4, 2018 7:25:15 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AttendanceReport generated by hbm2java
 */
@Entity
@Table(name="attendance_report"
    ,catalog="db_school"
)
public class AttendanceReport  implements java.io.Serializable {


     private Integer attendanceReportId;
     private AttendanceReportType attendanceReportType;
     private StudentRecordBs studentRecordBs;
     private Users users;
     private int totalPresents;
     private int totalAbsents;
     private Date attendanceRpDate;

    public AttendanceReport() {
    }

    public AttendanceReport(AttendanceReportType attendanceReportType, StudentRecordBs studentRecordBs, Users users, int totalPresents, int totalAbsents, Date attendanceRpDate) {
       this.attendanceReportType = attendanceReportType;
       this.studentRecordBs = studentRecordBs;
       this.users = users;
       this.totalPresents = totalPresents;
       this.totalAbsents = totalAbsents;
       this.attendanceRpDate = attendanceRpDate;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="attendance_report_id", unique=true, nullable=false)
    public Integer getAttendanceReportId() {
        return this.attendanceReportId;
    }
    
    public void setAttendanceReportId(Integer attendanceReportId) {
        this.attendanceReportId = attendanceReportId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="report_type_id", nullable=false)
    public AttendanceReportType getAttendanceReportType() {
        return this.attendanceReportType;
    }
    
    public void setAttendanceReportType(AttendanceReportType attendanceReportType) {
        this.attendanceReportType = attendanceReportType;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="record_bs_id", nullable=false)
    public StudentRecordBs getStudentRecordBs() {
        return this.studentRecordBs;
    }
    
    public void setStudentRecordBs(StudentRecordBs studentRecordBs) {
        this.studentRecordBs = studentRecordBs;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_id", nullable=false)
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }

    
    @Column(name="total_presents", nullable=false)
    public int getTotalPresents() {
        return this.totalPresents;
    }
    
    public void setTotalPresents(int totalPresents) {
        this.totalPresents = totalPresents;
    }

    
    @Column(name="total_absents", nullable=false)
    public int getTotalAbsents() {
        return this.totalAbsents;
    }
    
    public void setTotalAbsents(int totalAbsents) {
        this.totalAbsents = totalAbsents;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="attendance_rp_date", nullable=false, length=0)
    public Date getAttendanceRpDate() {
        return this.attendanceRpDate;
    }
    
    public void setAttendanceRpDate(Date attendanceRpDate) {
        this.attendanceRpDate = attendanceRpDate;
    }




}


