package com.school.domain;
// Generated Jul 4, 2018 7:25:15 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * AttendanceReportType generated by hbm2java
 */
@Entity
@Table(name="attendance_report_type"
    ,catalog="db_school"
)
public class AttendanceReportType  implements java.io.Serializable {


     private Integer reportTypeId;
     private String typeName;
     private Set<AttendanceReport> attendanceReports = new HashSet<AttendanceReport>(0);

    public AttendanceReportType() {
    }

	
    public AttendanceReportType(String typeName) {
        this.typeName = typeName;
    }
    public AttendanceReportType(String typeName, Set<AttendanceReport> attendanceReports) {
       this.typeName = typeName;
       this.attendanceReports = attendanceReports;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="report_type_id", unique=true, nullable=false)
    public Integer getReportTypeId() {
        return this.reportTypeId;
    }
    
    public void setReportTypeId(Integer reportTypeId) {
        this.reportTypeId = reportTypeId;
    }

    
    @Column(name="type_name", nullable=false, length=45)
    public String getTypeName() {
        return this.typeName;
    }
    
    public void setTypeName(String typeName) {
        this.typeName = typeName;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="attendanceReportType")
    public Set<AttendanceReport> getAttendanceReports() {
        return this.attendanceReports;
    }
    
    public void setAttendanceReports(Set<AttendanceReport> attendanceReports) {
        this.attendanceReports = attendanceReports;
    }




}


