package com.school.domain;
// Generated Jul 4, 2018 7:25:15 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Guardian generated by hbm2java
 */
@Entity
@Table(name="guardian"
    ,catalog="db_school"
)
public class Guardian  implements java.io.Serializable {


     private Integer guardianId;
     private String guardianName;
     private String address;
     private String phoneNo;
     private String mobileNo;
     private String email;
     private Set<Students> studentses = new HashSet<Students>(0);

    public Guardian() {
    }

	
    public Guardian(String guardianName, String address, String phoneNo, String mobileNo, String email) {
        this.guardianName = guardianName;
        this.address = address;
        this.phoneNo = phoneNo;
        this.mobileNo = mobileNo;
        this.email = email;
    }
    public Guardian(String guardianName, String address, String phoneNo, String mobileNo, String email, Set<Students> studentses) {
       this.guardianName = guardianName;
       this.address = address;
       this.phoneNo = phoneNo;
       this.mobileNo = mobileNo;
       this.email = email;
       this.studentses = studentses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="guardian_id", unique=true, nullable=false)
    public Integer getGuardianId() {
        return this.guardianId;
    }
    
    public void setGuardianId(Integer guardianId) {
        this.guardianId = guardianId;
    }

    
    @Column(name="guardian_name", nullable=false, length=45)
    public String getGuardianName() {
        return this.guardianName;
    }
    
    public void setGuardianName(String guardianName) {
        this.guardianName = guardianName;
    }

    
    @Column(name="address", nullable=false, length=45)
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }

    
    @Column(name="phone_no", nullable=false, length=45)
    public String getPhoneNo() {
        return this.phoneNo;
    }
    
    public void setPhoneNo(String phoneNo) {
        this.phoneNo = phoneNo;
    }

    
    @Column(name="mobile_no", nullable=false, length=45)
    public String getMobileNo() {
        return this.mobileNo;
    }
    
    public void setMobileNo(String mobileNo) {
        this.mobileNo = mobileNo;
    }

    
    @Column(name="email", nullable=false, length=45)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="guardian")
    public Set<Students> getStudentses() {
        return this.studentses;
    }
    
    public void setStudentses(Set<Students> studentses) {
        this.studentses = studentses;
    }




}


