package com.school.domain;
// Generated Jul 4, 2018 7:25:15 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * MarksPattern generated by hbm2java
 */
@Entity
@Table(name="marks_pattern"
    ,catalog="db_school"
)
public class MarksPattern  implements java.io.Serializable {


     private Integer marksPatternId;
     private int writtenMarks;
     private int mcqMarks;
     private int practicalMarks;
     private String patternName;
     private String note;
     private Set<Subjects> subjectses = new HashSet<Subjects>(0);

    public MarksPattern() {
    }

	
    public MarksPattern(int writtenMarks, int mcqMarks, int practicalMarks, String patternName, String note) {
        this.writtenMarks = writtenMarks;
        this.mcqMarks = mcqMarks;
        this.practicalMarks = practicalMarks;
        this.patternName = patternName;
        this.note = note;
    }
    public MarksPattern(int writtenMarks, int mcqMarks, int practicalMarks, String patternName, String note, Set<Subjects> subjectses) {
       this.writtenMarks = writtenMarks;
       this.mcqMarks = mcqMarks;
       this.practicalMarks = practicalMarks;
       this.patternName = patternName;
       this.note = note;
       this.subjectses = subjectses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="marks_pattern_id", unique=true, nullable=false)
    public Integer getMarksPatternId() {
        return this.marksPatternId;
    }
    
    public void setMarksPatternId(Integer marksPatternId) {
        this.marksPatternId = marksPatternId;
    }

    
    @Column(name="written_marks", nullable=false)
    public int getWrittenMarks() {
        return this.writtenMarks;
    }
    
    public void setWrittenMarks(int writtenMarks) {
        this.writtenMarks = writtenMarks;
    }

    
    @Column(name="mcq_marks", nullable=false)
    public int getMcqMarks() {
        return this.mcqMarks;
    }
    
    public void setMcqMarks(int mcqMarks) {
        this.mcqMarks = mcqMarks;
    }

    
    @Column(name="practical_marks", nullable=false)
    public int getPracticalMarks() {
        return this.practicalMarks;
    }
    
    public void setPracticalMarks(int practicalMarks) {
        this.practicalMarks = practicalMarks;
    }

    
    @Column(name="pattern_name", nullable=false, length=45)
    public String getPatternName() {
        return this.patternName;
    }
    
    public void setPatternName(String patternName) {
        this.patternName = patternName;
    }

    
    @Column(name="note", nullable=false, length=45)
    public String getNote() {
        return this.note;
    }
    
    public void setNote(String note) {
        this.note = note;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="marksPattern")
    public Set<Subjects> getSubjectses() {
        return this.subjectses;
    }
    
    public void setSubjectses(Set<Subjects> subjectses) {
        this.subjectses = subjectses;
    }




}


