package com.school.domain;
// Generated Jul 4, 2018 7:25:15 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Payment generated by hbm2java
 */
@Entity
@Table(name="payment"
    ,catalog="db_school"
)
public class Payment  implements java.io.Serializable {


     private Integer paymentId;
     private Users users;
     private String amount;
     private int monthNo;
     private Date paymentDate;
     private int paymentMethod;

    public Payment() {
    }

    public Payment(Users users, String amount, int monthNo, Date paymentDate, int paymentMethod) {
       this.users = users;
       this.amount = amount;
       this.monthNo = monthNo;
       this.paymentDate = paymentDate;
       this.paymentMethod = paymentMethod;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="payment_id", unique=true, nullable=false)
    public Integer getPaymentId() {
        return this.paymentId;
    }
    
    public void setPaymentId(Integer paymentId) {
        this.paymentId = paymentId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_id", nullable=false)
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }

    
    @Column(name="amount", nullable=false, length=45)
    public String getAmount() {
        return this.amount;
    }
    
    public void setAmount(String amount) {
        this.amount = amount;
    }

    
    @Column(name="month_no", nullable=false)
    public int getMonthNo() {
        return this.monthNo;
    }
    
    public void setMonthNo(int monthNo) {
        this.monthNo = monthNo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="payment_date", nullable=false, length=0)
    public Date getPaymentDate() {
        return this.paymentDate;
    }
    
    public void setPaymentDate(Date paymentDate) {
        this.paymentDate = paymentDate;
    }

    
    @Column(name="payment_method", nullable=false)
    public int getPaymentMethod() {
        return this.paymentMethod;
    }
    
    public void setPaymentMethod(int paymentMethod) {
        this.paymentMethod = paymentMethod;
    }




}


