package com.school.domain;
// Generated Jul 4, 2018 7:25:15 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Religion generated by hbm2java
 */
@Entity
@Table(name="religion"
    ,catalog="db_school"
)
public class Religion  implements java.io.Serializable {


     private Integer religionId;
     private String name;
     private Set<Users> userses = new HashSet<Users>(0);

    public Religion() {
    }

	
    public Religion(String name) {
        this.name = name;
    }
    public Religion(String name, Set<Users> userses) {
       this.name = name;
       this.userses = userses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="religion_id", unique=true, nullable=false)
    public Integer getReligionId() {
        return this.religionId;
    }
    
    public void setReligionId(Integer religionId) {
        this.religionId = religionId;
    }

    
    @Column(name="name", nullable=false, length=45)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="religion")
    public Set<Users> getUserses() {
        return this.userses;
    }
    
    public void setUserses(Set<Users> userses) {
        this.userses = userses;
    }




}


