package com.school.domain;
// Generated Jul 4, 2018 7:25:15 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * StudentRecordDt generated by hbm2java
 */
@Entity
@Table(name="student_record_dt"
    ,catalog="db_school"
)
public class StudentRecordDt  implements java.io.Serializable {


     private Integer recordDtId;
     private StudentRecordBs studentRecordBs;
     private Users users;
     private int rollNumber;
     private Set<Marks> markses = new HashSet<Marks>(0);
     private Set<Result> results = new HashSet<Result>(0);
     private Set<StudentPayment> studentPayments = new HashSet<StudentPayment>(0);
     private Set<ProgressReport> progressReports = new HashSet<ProgressReport>(0);

    public StudentRecordDt() {
    }

	
    public StudentRecordDt(StudentRecordBs studentRecordBs, Users users, int rollNumber) {
        this.studentRecordBs = studentRecordBs;
        this.users = users;
        this.rollNumber = rollNumber;
    }
    public StudentRecordDt(StudentRecordBs studentRecordBs, Users users, int rollNumber, Set<Marks> markses, Set<Result> results, Set<StudentPayment> studentPayments, Set<ProgressReport> progressReports) {
       this.studentRecordBs = studentRecordBs;
       this.users = users;
       this.rollNumber = rollNumber;
       this.markses = markses;
       this.results = results;
       this.studentPayments = studentPayments;
       this.progressReports = progressReports;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="record_dt_id", unique=true, nullable=false)
    public Integer getRecordDtId() {
        return this.recordDtId;
    }
    
    public void setRecordDtId(Integer recordDtId) {
        this.recordDtId = recordDtId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="record_bs_id", nullable=false)
    public StudentRecordBs getStudentRecordBs() {
        return this.studentRecordBs;
    }
    
    public void setStudentRecordBs(StudentRecordBs studentRecordBs) {
        this.studentRecordBs = studentRecordBs;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_id", nullable=false)
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }

    
    @Column(name="roll_number", nullable=false)
    public int getRollNumber() {
        return this.rollNumber;
    }
    
    public void setRollNumber(int rollNumber) {
        this.rollNumber = rollNumber;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="studentRecordDt")
    public Set<Marks> getMarkses() {
        return this.markses;
    }
    
    public void setMarkses(Set<Marks> markses) {
        this.markses = markses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="studentRecordDt")
    public Set<Result> getResults() {
        return this.results;
    }
    
    public void setResults(Set<Result> results) {
        this.results = results;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="studentRecordDt")
    public Set<StudentPayment> getStudentPayments() {
        return this.studentPayments;
    }
    
    public void setStudentPayments(Set<StudentPayment> studentPayments) {
        this.studentPayments = studentPayments;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="studentRecordDt")
    public Set<ProgressReport> getProgressReports() {
        return this.progressReports;
    }
    
    public void setProgressReports(Set<ProgressReport> progressReports) {
        this.progressReports = progressReports;
    }




}


