package com.school.domain;
// Generated Jul 4, 2018 7:25:15 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Subjects generated by hbm2java
 */
@Entity
@Table(name="subjects"
    ,catalog="db_school"
)
public class Subjects  implements java.io.Serializable {


     private Integer subjectId;
     private Groups groups;
     private MarksPattern marksPattern;
     private String subjectName;
     private Set<TeacherClasses> teacherClasseses = new HashSet<TeacherClasses>(0);
     private Set<Marks> markses = new HashSet<Marks>(0);

    public Subjects() {
    }

	
    public Subjects(Groups groups, MarksPattern marksPattern, String subjectName) {
        this.groups = groups;
        this.marksPattern = marksPattern;
        this.subjectName = subjectName;
    }
    public Subjects(Groups groups, MarksPattern marksPattern, String subjectName, Set<TeacherClasses> teacherClasseses, Set<Marks> markses) {
       this.groups = groups;
       this.marksPattern = marksPattern;
       this.subjectName = subjectName;
       this.teacherClasseses = teacherClasseses;
       this.markses = markses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="subject_id", unique=true, nullable=false)
    public Integer getSubjectId() {
        return this.subjectId;
    }
    
    public void setSubjectId(Integer subjectId) {
        this.subjectId = subjectId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="group_id", nullable=false)
    public Groups getGroups() {
        return this.groups;
    }
    
    public void setGroups(Groups groups) {
        this.groups = groups;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="marks_pattern_id", nullable=false)
    public MarksPattern getMarksPattern() {
        return this.marksPattern;
    }
    
    public void setMarksPattern(MarksPattern marksPattern) {
        this.marksPattern = marksPattern;
    }

    
    @Column(name="subject_name", nullable=false, length=45)
    public String getSubjectName() {
        return this.subjectName;
    }
    
    public void setSubjectName(String subjectName) {
        this.subjectName = subjectName;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="subjects")
    public Set<TeacherClasses> getTeacherClasseses() {
        return this.teacherClasseses;
    }
    
    public void setTeacherClasseses(Set<TeacherClasses> teacherClasseses) {
        this.teacherClasseses = teacherClasseses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="subjects")
    public Set<Marks> getMarkses() {
        return this.markses;
    }
    
    public void setMarkses(Set<Marks> markses) {
        this.markses = markses;
    }




}


