package com.school.domain;
// Generated Jul 4, 2018 7:25:15 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SubScholarship generated by hbm2java
 */
@Entity
@Table(name="sub_scholarship"
    ,catalog="db_school"
)
public class SubScholarship  implements java.io.Serializable {


     private Integer subScholId;
     private int classId;
     private double boyAmount;
     private double girlAmount;
     private double eligbleAttPd;
     private double eligibleResult;

    public SubScholarship() {
    }

    public SubScholarship(int classId, double boyAmount, double girlAmount, double eligbleAttPd, double eligibleResult) {
       this.classId = classId;
       this.boyAmount = boyAmount;
       this.girlAmount = girlAmount;
       this.eligbleAttPd = eligbleAttPd;
       this.eligibleResult = eligibleResult;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="sub_schol_id", unique=true, nullable=false)
    public Integer getSubScholId() {
        return this.subScholId;
    }
    
    public void setSubScholId(Integer subScholId) {
        this.subScholId = subScholId;
    }

    
    @Column(name="class_id", nullable=false)
    public int getClassId() {
        return this.classId;
    }
    
    public void setClassId(int classId) {
        this.classId = classId;
    }

    
    @Column(name="boy_amount", nullable=false, precision=22, scale=0)
    public double getBoyAmount() {
        return this.boyAmount;
    }
    
    public void setBoyAmount(double boyAmount) {
        this.boyAmount = boyAmount;
    }

    
    @Column(name="girl_amount", nullable=false, precision=22, scale=0)
    public double getGirlAmount() {
        return this.girlAmount;
    }
    
    public void setGirlAmount(double girlAmount) {
        this.girlAmount = girlAmount;
    }

    
    @Column(name="eligble_att_pd", nullable=false, precision=22, scale=0)
    public double getEligbleAttPd() {
        return this.eligbleAttPd;
    }
    
    public void setEligbleAttPd(double eligbleAttPd) {
        this.eligbleAttPd = eligbleAttPd;
    }

    
    @Column(name="eligible_result", nullable=false, precision=22, scale=0)
    public double getEligibleResult() {
        return this.eligibleResult;
    }
    
    public void setEligibleResult(double eligibleResult) {
        this.eligibleResult = eligibleResult;
    }




}


